# Permalinks
permalink:           pretty

# Setup
title:               P.D. Ilhardt
tagline:             A Data Science Blog
url:                 http://peterilhardt.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Peter Ilhardt
  url:               https://www.linkedin.com/in/peterilhardt/
  email:             pilhardt@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/peterilhardt

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
